### ISSUE TITLE
LEM landing warning alarm sound in "First Man" movie

### ISSUE THREAD

**Issue by hydrogenpi** [orbiternassp/NASSP#445]
Did it really sound like that? I don't recall in Apollo 13 movie that LEM made that sort of alarm noise... Or did they take a creative liberty of sorts? I also can't find that alarm sound in NASSP either.

**Comment by hydrogenpi** [comment]
The reason I am asking is I preordered the 4k of First Man because the graphics are just awesome, better than the Nvidia GTX/RTX  VXGI/ray-tracing demo of Apollo 11, and I would like to use the alarm sound as for my own phone alarm customization but I want to know if it is realistic like does the real LEM sound like that or not?

**Comment by indy91** [comment]
I haven't seen First Man yet, so I don't know how it sounds there. Here is our sound file for the LM master alarm: https://github.com/dseagrav/NASSP/blob/Orbiter2016/Sound/ProjectApollo/alarm_lm.wav This is of course a very short file, but it's this 3000 Hz tone played continuously. Sounds quite horrible, right? Maybe this link illustrates it better: http://szynalski.com/tone#3000,v0.75

**Comment by hydrogenpi** [comment]
okay I checked, it sounds nothing like it.

I'm thinking the movie took some artistic licenses for sure

**Comment by hydrogenpi** [comment]
and the shaky camera was too shaky
