### ISSUE TITLE
Cannot start Orbitersim at all after upgrading to rtx2080ti

### ISSUE THREAD

**Issue by hydrogenpi** [orbiternassp/NASSP#455]
Can someone help? I heard there is a dx9/11 wrapper for orbitersim but i haven't been able  to get that running either

The default Orbitersim 2016 won't start with the latest rtx2080ti card regardless of what new or old version of nvidia drivers I tried... and I cannot seem to even get it to start in software mode rendering...

Is there a workaround anyone found yet?

**Comment by indy91** [comment]
As this is an issue with Orbiter and not NASSP directly you probably better ask this on the Orbiter Forum, I'm sure they will be able to help you.
