### ISSUE TITLE
Checklists don't use "POT TK IN vlv" properly

### ISSUE THREAD

**Issue by mmontour** [orbiternassp/NASSP#508]
The checklists are not using the Potable Tank Inlet valve properly in two places:

1. The Apollo 11 flight plan section for chlorinating the potable tank currently reads:
```
POT TK IN vlv - OPEN
(chlorination not simulated yet)
POT TK IN vlv - CLOSE
```
In the actual checklist there is a step to verify that the valve is open but it is left open at the end of the procedure so that water from the fuel cells can flow into the potable tank. 

2. The "CSM Default Checklists" section for performing a waste water dump does not mention "POT TK IN vlv" at all. The actual procedure includes a step to close the Potable inlet while the dump is in progress and then to open it afterward. My guess is that this was to prevent leakage from the potable tank if a check valve failed. 

Reference: https://history.nasa.gov/afj/ap11fj/a11-csmocindex.html pages F10-13 and F10-14.

**Comment by rcflyinghokie** [comment]
This has been verified and fixed on Apollo 10 and 11 Checklists.  Waste water dump procedures on Apollo 8 & 9 didnt include the potable tank, so it was not added to those checklists.
