### ISSUE TITLE
FDAI is solid white. It does not load properly.

### ISSUE THREAD

**Issue by eev1a** [orbiternassp/NASSP#509]
When FDAI is on, it is completely solid white. It does not load properly.
When it is off, it loads properly.

Here's a picture.
![kuva](https://user-images.githubusercontent.com/53858176/62611216-d4f43b80-b90d-11e9-9818-679a39dbaa74.png)

**Comment by indy91** [comment]
This happens when you load the Apollo 11 T-30s scenario? With a recent NASSP 8.0 Beta release, and Orbiter Beta and DX9 Client? Any particular Orbiter settings activated? FDAI smooth scrolling?

**Comment by indy91** [comment]
And it happens with both FDAIs? Not only IMU or GDC driven FDAI?

**Comment by indy91** [comment]
The FDAI is also implemented in a bit of a weird way, so this could be some graphics setting or even grpahics card issue.

**Comment by eev1a** [comment]
All yes. Bot FDAIs, smooth scrolling, everything.

**Comment by indy91** [comment]
Does disabling smooth scrolling fix the issue? I have the feeling I have seen this issue before, but I can't remember where and when...

**Comment by lotisully86** [comment]
The fdai’s are part of the main panel ‘static’ image bitmap, that’s why they appear when fdai is off, they aren’t loading properly they just aren’t loading at all. 

When set to on the panel ‘blanks’ out the space for the two fdai’s and creates the 3D  simulation fdai using files from the textures directory. Check to make sure your textures directory is up to date and not missing files. If you are using orbiter beta, and set it up correctly, I would copy this directory into your previous orbiter 2016 install textures directory. In other words you set beta up to use 2016 textures, every time you update NASSP textures on beta, they need to be moved to/updated/copied in 2016 as well. Hope this helps

**Comment by jalexb88** [comment]
See this post: https://www.orbiter-forum.com/showthread.php?p=596379&postcount=9 I think that should fix the problem.

**Comment by eev1a** [comment]
> 
> 
> See this post: https://www.orbiter-forum.com/showthread.php?p=596379&postcount=9 I think that should fix the problem.

It didn't fix.

**Comment by Thymo-** [comment]
Closed due to inactivity.
