### ISSUE TITLE
CTD when opening the CM forward hatch

### ISSUE THREAD

**Issue by indy91** [orbiternassp/NASSP#572]
The easiest way to replicate this bug is as follows.

-Load a scenario with the CSM and LM docked, and the LM already pressurized.
-Go to the outside view at least once
-Perform CM/SM separation (CM and LM still docked)
-Try opening the CM forward hatch and the CTD will occur

This bug is very likely caused by the Saturn::ProbeVis function, the CTD doesn't occur if the function isn't used.

**Comment by jalexb88** [comment]
Issue should be fixed with latest CMVC branch merge.
