### ISSUE TITLE
Problem with TLI on Apollo 11

### ISSUE THREAD

**Issue by RL77** [orbiternassp/NASSP#597]
Hello,

Today I started a new Apollo 11 mission, I haven't done it in a while. I detected a problem with TLI. Right after the ignition of the SIVB, the dV countdown on the EMS disappears, the FDAI 2 goes black, we hear the Orbiter's ATC saying "You are cleared to land" and then the simulator goes down. I was using version 1638, after that I saw that version 1639 and 1640 was released today. I tried with both and the same thing happens. I recorded a video so you can see it better!

Video: https://we.tl/t-efg5X19nO1

In the meantime I went to see more closely what happens (I'm editing this), and I noticed that the altimeter is going to zero. I decided to repeat it again, and see what was going on in the outside view. The ship simply falls and collides with the Earth's surface in about 5 sec.

Thanks

**Comment by indy91** [comment]
Interesting. Looks like some sort of divide by zero issue to me. Something that breaks Orbiter enough to cause the state of the spacecraft to be all messed up, including EMS accelerometer and all. At least this issue doesn't happen in all scenarios, I am not getting it in the Apollo 11 Before TLI mission scenario that comes with NASSP.

Do you have a scenario saved where I can replicate your issue? That would help a lot. Thanks!

**Comment by RL77** [comment]
Yes I have the last savefile I made yesterday, which starts at the same GET as in the video I sent, about 3min 30 sec from TLI. Here it is:
https://we.tl/t-7qX6aGYC19

I can send all the mission saves files if you need them!

**Comment by indy91** [comment]
Found the issue. The LVDC isn't saving/loading two variables which are only calculated until Timebase 6 starts, but are then used shortly after ignition. So the values of the variables are random and cause some calculations to grow to infinity. And there isn't really a check against that and suddenly there is a lot of numbers that have NaN as their value.

Short term solution, don't save/load between TB6 initiation and TLI cutoff, so in your case use a scenario before TB6. TB6 starts when the S-II Sep light is being switched on again for the first time, shortly before you start up the event timer. And I will add saving/loading for those variables for which it is missing. And I guess the LVDC code also needs some protection against causing these issues, even if the LVDC itself has terrible problems.

**Comment by indy91** [comment]
Bug is probably fixed now. But your scenario is of course still broken, as it doesn't have the two variables I mentioned saved. Just revert to an earlier scenario and you should be able to continue.

**Comment by RL77** [comment]
Ok, im going to make a load before TB6 and not  save until TLI is finished. 

Thanks!

**Comment by RL77** [comment]
It worked! TLI went well!  Just a question. Normally when I do a mission, I keep the version of NASSP that I started with until the end of that same mission.I only update again when I start a new mission. Is it more advisable to do this, or is it ok to update during a mission?

**Comment by indy91** [comment]
It's usually more advisable to not update. Most updates will not break scenarios, but there is always a chance that some change does something unexpected to an ongoing mission.

**Comment by RL77** [comment]
Ok,, it’s because I think exactly that, that I didn’t update.
 Thank you for your help.
