### ISSUE TITLE
LM Systems Implementation Phase 1

### ISSUE THREAD

**Issue by dseagrav** [orbiternassp/NASSP#6]
LM systems implementation for Apollo 9/10 features. Hardware used or tested in Apollo 9/10 should be able to perform the functions tested during those missions.

**Comment by rcflyinghokie** [comment]
#603

**Comment by rcflyinghokie** [comment]
Most LM systems have been implemented, is there anything else major that is missing other than a few heaters or changes that would be involved in a major EPS or PROP rework?

**Comment by rcflyinghokie** [comment]
Doubling back to this, I think the LM can handle 9 and 10 fully flown currently, only exceptions are specific spacecraft panels and AGS software plus flight test software flown on 9.

**Comment by maxq519** [comment]
I'd say this can be closed at this point
