### ISSUE TITLE
Rate needles move inversely

### ISSUE THREAD

**Issue by RL77** [orbiternassp/NASSP#601]
Hi,

As I said in the previous Issue, I started a new Apollo 11 mission this weekend. I noticed right after TLI that the rate needles in the FDAIs move inversely in these versions of NASSP, that is, if I roll to the right, for example, the roll rate needle moves to the left instead. The same is true for pitch and yaw. It wasn't like that in previous versions. If I roll to the right, isn't the roll rate needle supposed to move to the right too? I checked and the same thing happens in the LEM. In fact, it even makes it a little confusing to rotate the spacecraft. Is this a bug?

Thanks

**Comment by n7275** [comment]
This was a recent change to the CSM and LM and is not a bug. https://www.orbiter-forum.com/threads/fdai-rate-indicators-correct.39741/

It's confusing for us as well at times.

**Comment by RL77** [comment]
Okay so now this is correct! It looks like I'm going to have to get used to it :). Thanks for the answer and the link, we are always learning!
